clc
disp('*****Save Data*******')
disp(class(v))
disp(fieldnames(v))
disp('****Data Type of Fields********')
disp(class(v.time))
disp(class(v.signals))
disp(class(v.blockName))
disp('**** signals *****')
disp(fieldnames(v.signals))
disp(class(v.signals.values))
disp('**** values *****')
disp(v.signals.values(1))
disp(v.signals.values(end))
